CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone VARCHAR(20) UNIQUE,
    email VARCHAR(255) UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    profile_for VARCHAR(40) NOT NULL DEFAULT 'self',
    relationship VARCHAR(80),
    registration_location VARCHAR(200),
    is_phone_verified BOOLEAN NOT NULL DEFAULT FALSE,
    is_email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    role VARCHAR(30) NOT NULL DEFAULT 'user',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS profiles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER UNIQUE NOT NULL,
    name VARCHAR(120),
    gender VARCHAR(30),
    date_of_birth DATE,
    gothra VARCHAR(120),
    community VARCHAR(120),
    education VARCHAR(200),
    profession VARCHAR(200),
    income VARCHAR(100),
    height_cm INTEGER,
    permanent_address TEXT,
    preferred_location VARCHAR(200),
    family_details TEXT,
    photo_path VARCHAR(500),
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    rejection_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS partner_preferences (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER UNIQUE NOT NULL,
    min_age INTEGER,
    max_age INTEGER,
    min_height_cm INTEGER,
    max_height_cm INTEGER,
    income VARCHAR(100),
    education VARCHAR(200),
    profession VARCHAR(200),
    location VARCHAR(200),
    community VARCHAR(120),
    other_criteria TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS otps (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact VARCHAR(255) NOT NULL,
    code_hash VARCHAR(128) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS verifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER UNIQUE NOT NULL,
    parent_mobile VARCHAR(20),
    parent_status VARCHAR(30) NOT NULL DEFAULT 'NOT_STARTED',
    identity_status VARCHAR(30) NOT NULL DEFAULT 'NOT_STARTED',
    identity_reference VARCHAR(120),
    notes TEXT,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_users_phone ON users(phone);
CREATE INDEX IF NOT EXISTS ix_users_email ON users(email);
CREATE INDEX IF NOT EXISTS ix_profiles_user_id ON profiles(user_id);
CREATE INDEX IF NOT EXISTS ix_profiles_status ON profiles(status);
CREATE INDEX IF NOT EXISTS ix_partner_preferences_user_id ON partner_preferences(user_id);
CREATE INDEX IF NOT EXISTS ix_otps_contact ON otps(contact);
CREATE INDEX IF NOT EXISTS ix_verifications_user_id ON verifications(user_id);

CREATE TABLE IF NOT EXISTS interests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    receiver_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_interest_sender_receiver UNIQUE (sender_id, receiver_id),
    CONSTRAINT chk_interest_status CHECK (status IN ('PENDING','ACCEPTED','REJECTED','WITHDRAWN'))
);
CREATE INDEX IF NOT EXISTS ix_interests_sender_id ON interests(sender_id);
CREATE INDEX IF NOT EXISTS ix_interests_receiver_id ON interests(receiver_id);
CREATE INDEX IF NOT EXISTS ix_interests_status ON interests(status);

CREATE TABLE IF NOT EXISTS matches (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_one_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    user_two_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    score INTEGER,
    source VARCHAR(50) NOT NULL DEFAULT 'INTEREST_ACCEPTED',
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_match_pair UNIQUE (user_one_id, user_two_id),
    CONSTRAINT chk_match_different_users CHECK (user_one_id <> user_two_id)
);
CREATE INDEX IF NOT EXISTS ix_matches_user_one_id ON matches(user_one_id);
CREATE INDEX IF NOT EXISTS ix_matches_user_two_id ON matches(user_two_id);

CREATE TABLE IF NOT EXISTS shortlists (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    profile_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_shortlist_user_profile UNIQUE (user_id, profile_user_id),
    CONSTRAINT chk_shortlist_different_users CHECK (user_id <> profile_user_id)
);
CREATE INDEX IF NOT EXISTS ix_shortlists_user_id ON shortlists(user_id);
CREATE INDEX IF NOT EXISTS ix_shortlists_profile_user_id ON shortlists(profile_user_id);

CREATE TABLE IF NOT EXISTS notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(160) NOT NULL,
    message VARCHAR(500) NOT NULL,
    payload JSONB,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_notifications_recipient_id ON notifications(recipient_id);
CREATE INDEX IF NOT EXISTS ix_notifications_type ON notifications(type);
CREATE INDEX IF NOT EXISTS ix_notifications_is_read ON notifications(is_read);
