from datetime import datetime, timezone

from sqlalchemy import (
    Boolean,
    DateTime,
    ForeignKey,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.db.session import Base


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


class PaymentOrder(Base):
    """
    Direct UPI payment order.

    Flow:

        PENDING
           ↓
        SUBMITTED
           ↓
        VERIFIED → subscription activated

        SUBMITTED → REJECTED
                         ↓
                    user can resubmit

    No payment gateway is used.
    """

    __tablename__ = "payment_orders"

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
    )

    user_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("users.id"),
        index=True,
        nullable=False,
    )

    plan_code: Mapped[str] = mapped_column(
        String(40),
        nullable=False,
        index=True,
    )

    # Original plan price.
    amount_inr: Mapped[float] = mapped_column(
        Numeric(10, 2),
        nullable=False,
    )

    # Discount applied by coupon.
    discount_inr: Mapped[float] = mapped_column(
        Numeric(10, 2),
        nullable=False,
        default=0,
    )

    # Final amount user must pay.
    final_amount_inr: Mapped[float] = mapped_column(
        Numeric(10, 2),
        nullable=False,
    )

    # UPI account receiving payment.
    upi_vpa: Mapped[str] = mapped_column(
        String(120),
        nullable=False,
    )

    transaction_note: Mapped[str] = mapped_column(
        String(120),
        nullable=False,
    )

    # Unique transaction reference generated by our system.
    transaction_ref: Mapped[str] = mapped_column(
        String(80),
        nullable=False,
        unique=True,
        index=True,
    )

    # UTR entered by customer after payment.
    utr_reference: Mapped[str | None] = mapped_column(
        String(60),
        nullable=True,
        index=True,
    )

    # Optional coupon.
    coupon_id: Mapped[int | None] = mapped_column(
        Integer,
        ForeignKey("coupons.id"),
        nullable=True,
    )

    status: Mapped[str] = mapped_column(
        String(20),
        default="PENDING",
        nullable=False,
        index=True,
    )

    rejection_reason: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    verified_by_user_id: Mapped[int | None] = mapped_column(
        Integer,
        ForeignKey("users.id"),
        nullable=True,
    )

    verified_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=utcnow,
        nullable=False,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=utcnow,
        onupdate=utcnow,
        nullable=False,
    )


class Subscription(Base):
    """
    User subscription.

    Only an ADMIN verified payment can activate this record.
    """

    __tablename__ = "subscriptions"

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
    )

    user_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("users.id"),
        index=True,
        nullable=False,
    )

    plan_code: Mapped[str] = mapped_column(
        String(40),
        nullable=False,
        index=True,
    )

    start_date: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
    )

    end_date: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
    )

    is_active: Mapped[bool] = mapped_column(
        Boolean,
        default=True,
        nullable=False,
        index=True,
    )

    source_order_id: Mapped[int | None] = mapped_column(
        Integer,
        ForeignKey("payment_orders.id"),
        nullable=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=utcnow,
        nullable=False,
    )


class Coupon(Base):
    """
    Admin-created discount coupon.

    discount_type:
        PERCENT
        FIXED
    """

    __tablename__ = "coupons"

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
    )

    code: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        unique=True,
        index=True,
    )

    discount_type: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
    )

    discount_value: Mapped[float] = mapped_column(
        Numeric(10, 2),
        nullable=False,
    )

    max_uses: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
    )

    used_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
    )

    valid_from: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    valid_until: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        index=True,
    )

    created_by_admin_id: Mapped[int | None] = mapped_column(
        Integer,
        ForeignKey("users.id"),
        nullable=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utcnow,
    )


class CouponUsage(Base):
    """
    Prevents one user from repeatedly using the same coupon.
    """

    __tablename__ = "coupon_usages"

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
    )

    coupon_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("coupons.id"),
        nullable=False,
        index=True,
    )

    user_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("users.id"),
        nullable=False,
        index=True,
    )

    payment_order_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("payment_orders.id"),
        nullable=False,
    )

    discount_amount: Mapped[float] = mapped_column(
        Numeric(10, 2),
        nullable=False,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utcnow,
    )

    __table_args__ = (
        UniqueConstraint(
            "coupon_id",
            "user_id",
            name="uq_coupon_user_once",
        ),
    )