-- MauryaShaadi Phase 6: production subscription/payment foundation.
-- Run this against an existing Phase-3 database before production.
-- New installations can rely on SQLAlchemy metadata plus the seed plan logic.

CREATE TABLE IF NOT EXISTS subscription_plans (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    price_inr NUMERIC(10,2) NOT NULL,
    duration_days INTEGER NOT NULL DEFAULT 30,
    max_match_score INTEGER NOT NULL DEFAULT 50,
    features TEXT NOT NULL DEFAULT '[]',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS coupons (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) UNIQUE NOT NULL,
    discount_type VARCHAR(20) NOT NULL,
    discount_value NUMERIC(10,2) NOT NULL,
    max_discount_inr NUMERIC(10,2),
    min_order_amount_inr NUMERIC(10,2),
    usage_limit INTEGER,
    used_count INTEGER NOT NULL DEFAULT 0,
    per_user_limit INTEGER NOT NULL DEFAULT 1,
    valid_from TIMESTAMPTZ NOT NULL,
    valid_until TIMESTAMPTZ NOT NULL,
    applicable_plan_code VARCHAR(40),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by_user_id INTEGER REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER UNIQUE NOT NULL REFERENCES payment_orders(id),
    user_id INTEGER NOT NULL REFERENCES users(id),
    gateway VARCHAR(30) NOT NULL DEFAULT 'razorpay',
    gateway_payment_id VARCHAR(80) UNIQUE NOT NULL,
    gateway_signature VARCHAR(128),
    payment_method VARCHAR(40),
    amount_inr NUMERIC(10,2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'INR',
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    gateway_response TEXT,
    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS coupon_usages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_id INTEGER NOT NULL REFERENCES coupons(id),
    user_id INTEGER NOT NULL REFERENCES users(id),
    order_id INTEGER NOT NULL REFERENCES payment_orders(id),
    discount_amount_inr NUMERIC(10,2) NOT NULL,
    used_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_coupon_usage_order UNIQUE (coupon_id, user_id, order_id)
);

CREATE TABLE IF NOT EXISTS payment_webhook_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(120) UNIQUE NOT NULL,
    event_type VARCHAR(80) NOT NULL,
    payload TEXT NOT NULL,
    processed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL
);

ALTER TABLE payment_orders ADD COLUMN IF NOT EXISTS coupon_id INTEGER;
ALTER TABLE payment_orders ADD COLUMN IF NOT EXISTS order_reference VARCHAR(64);
ALTER TABLE payment_orders ADD COLUMN IF NOT EXISTS gateway VARCHAR(30) DEFAULT 'razorpay';
ALTER TABLE payment_orders ADD COLUMN IF NOT EXISTS gateway_order_id VARCHAR(80);
ALTER TABLE payment_orders ADD COLUMN IF NOT EXISTS original_amount_inr NUMERIC(10,2);
ALTER TABLE payment_orders ADD COLUMN IF NOT EXISTS discount_amount_inr NUMERIC(10,2) DEFAULT 0;
ALTER TABLE payment_orders ADD COLUMN IF NOT EXISTS tax_amount_inr NUMERIC(10,2) DEFAULT 0;
ALTER TABLE payment_orders ADD COLUMN IF NOT EXISTS final_amount_inr NUMERIC(10,2);
ALTER TABLE payment_orders ADD COLUMN IF NOT EXISTS currency VARCHAR(3) DEFAULT 'INR';
ALTER TABLE payment_orders ADD COLUMN IF NOT EXISTS failure_reason TEXT;

UPDATE payment_orders SET order_reference = COALESCE(order_reference, 'LEGACY-' || id::text);
UPDATE payment_orders SET original_amount_inr = COALESCE(original_amount_inr, amount_inr);
UPDATE payment_orders SET final_amount_inr = COALESCE(final_amount_inr, amount_inr);
UPDATE payment_orders SET discount_amount_inr = COALESCE(discount_amount_inr, 0), tax_amount_inr = COALESCE(tax_amount_inr, 0), currency = COALESCE(currency, 'INR'), gateway = COALESCE(gateway, 'legacy_upi');

CREATE UNIQUE INDEX IF NOT EXISTS uq_payment_orders_order_reference ON payment_orders(order_reference);
CREATE UNIQUE INDEX IF NOT EXISTS uq_payment_orders_gateway_order_id ON payment_orders(gateway_order_id) WHERE gateway_order_id IS NOT NULL;

ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS payment_id INTEGER;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS status VARCHAR(30);
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS auto_renew BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ;
UPDATE subscriptions SET status = CASE WHEN is_active = TRUE AND end_date >= NOW() THEN 'ACTIVE' WHEN is_active = TRUE THEN 'EXPIRED' ELSE 'CANCELLED' END WHERE status IS NULL;

INSERT INTO subscription_plans (code, name, description, price_inr, duration_days, max_match_score, features, is_active, display_order, created_at, updated_at)
VALUES
('AI_DISCOVERY', 'AI Discovery', 'AI compatibility recommendations up to 50%.', 49.00, 30, 50, '["AI compatibility score","Recommendations up to 50%","Basic AI matching insights"]', TRUE, 1, NOW(), NOW()),
('AI_SMART', 'AI Smart Match', 'AI compatibility recommendations up to 75%.', 199.00, 30, 75, '["Everything in AI Discovery","Recommendations up to 75%","Higher compatibility recommendations","Priority recommendations"]', TRUE, 2, NOW(), NOW()),
('AI_PREMIUM', 'AI Premium Match', 'Access the highest compatible recommendations, up to 100%, when available.', 499.00, 30, 100, '["Everything in AI Smart Match","Recommendations up to 100%","Premium recommendation priority","Advanced AI compatibility insights"]', TRUE, 3, NOW(), NOW())
ON CONFLICT (code) DO NOTHING;
