-- MauryaShaadi Phase 5 migration
-- Run this against an existing PostgreSQL database if you do not want to rely on SQLAlchemy create_all.

CREATE TABLE IF NOT EXISTS interests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    receiver_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_interest_sender_receiver UNIQUE (sender_id, receiver_id),
    CONSTRAINT chk_interest_status CHECK (status IN ('PENDING','ACCEPTED','REJECTED','WITHDRAWN'))
);
CREATE INDEX IF NOT EXISTS ix_interests_sender_id ON interests(sender_id);
CREATE INDEX IF NOT EXISTS ix_interests_receiver_id ON interests(receiver_id);
CREATE INDEX IF NOT EXISTS ix_interests_status ON interests(status);

CREATE TABLE IF NOT EXISTS matches (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_one_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    user_two_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    score INTEGER,
    source VARCHAR(50) NOT NULL DEFAULT 'INTEREST_ACCEPTED',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_match_pair UNIQUE (user_one_id, user_two_id),
    CONSTRAINT chk_match_different_users CHECK (user_one_id <> user_two_id)
);
CREATE INDEX IF NOT EXISTS ix_matches_user_one_id ON matches(user_one_id);
CREATE INDEX IF NOT EXISTS ix_matches_user_two_id ON matches(user_two_id);

CREATE TABLE IF NOT EXISTS shortlists (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    profile_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_shortlist_user_profile UNIQUE (user_id, profile_user_id),
    CONSTRAINT chk_shortlist_different_users CHECK (user_id <> profile_user_id)
);
CREATE INDEX IF NOT EXISTS ix_shortlists_user_id ON shortlists(user_id);
CREATE INDEX IF NOT EXISTS ix_shortlists_profile_user_id ON shortlists(profile_user_id);

CREATE TABLE IF NOT EXISTS notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(160) NOT NULL,
    message VARCHAR(500) NOT NULL,
    payload JSONB,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_notifications_recipient_id ON notifications(recipient_id);
CREATE INDEX IF NOT EXISTS ix_notifications_type ON notifications(type);
CREATE INDEX IF NOT EXISTS ix_notifications_is_read ON notifications(is_read);
